# Generated by Django 4.2.6 on 2025-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_iqacmember_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQACMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='iqac_minutes/')),
            ],
        ),
    ]
