# Generated by Django 4.2.6 on 2025-04-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_iqacminute'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='statement_compliance/')),
            ],
        ),
    ]
