# Generated by Django 4.2.6 on 2025-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_statementcompliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementcompliance',
            old_name='file',
            new_name='pdf',
        ),
    ]
