# Generated by Django 4.2.6 on 2025-04-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_file_statementcompliance_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='aqar/')),
            ],
        ),
        migrations.CreateModel(
            name='AQARReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='aqar_report/')),
            ],
        ),
    ]
