# Generated by Django 4.2.6 on 2025-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_aqar_aqarreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='aishe/')),
            ],
        ),
    ]
