# Generated by Django 4.2.6 on 2025-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_bestpractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='student_satisfaction/')),
            ],
        ),
    ]
