# Generated by Django 4.2.6 on 2025-04-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_employee_name_alter_employee_position'),
        ('myapp', '0013_academiccalendar'),
    ]

    operations = [
    ]
