# Generated by Django 4.2.6 on 2025-04-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_feedback'),
        ('myapp', '0014_merge_20250409_0444'),
    ]

    operations = [
    ]
