# Generated by Django 4.2.6 on 2025-04-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_exam'),
        ('myapp', '0015_merge_0014_feedback_0014_merge_20250409_0444'),
    ]

    operations = [
    ]
