# Generated by Django 4.2.6 on 2025-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='additional_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='awards_honours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='books_published',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='major_minor_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='papers_presented',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_webpage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phd_mphil_projects_guided',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='seminars_conferences_organised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_work_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Head Of Department & Professor', 'Head Of Department & Professor'), ('Head of the Department & Associate Professor', 'Head of the Department & Associate Professor'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Guest Lecturer', 'Guest Lecturer'), ('Office Staff', 'Office Staff')], max_length=255),
        ),
    ]
