# Generated by Django 4.2.6 on 2025-05-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_merge_20250418_0911'),
        ('myapp', '0017_employee_additional_responsibilities_and_more'),
    ]

    operations = [
    ]
