# Generated by Django 4.2.6 on 2025-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_employee_additional_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='seniority',
            field=models.DateField(blank=True, null=True),
        ),
    ]
