# Generated by Django 4.2.6 on 2025-06-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_employee_seniority'),
        ('myapp', '0018_merge_20250508_0936'),
    ]

    operations = [
    ]
