# Generated by Django 4.2.6 on 2025-05-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_employee_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Head Of Department & Professor', 'Head Of Department & Professor'), ('Head of the Department & Associate Professor', 'Head of the Department & Associate Professor'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Guest Lecturer', 'Guest Lecturer'), ('Senior Superintendent', 'Senior Superintendent'), ('Head Accountant', 'Head Accountant'), ('Clerk ', 'Clerk '), ('Librarian', 'Librarian'), ('Office Staff', 'Office Staff')], max_length=255),
        ),
    ]
