# Generated by Django 4.2.6 on 2025-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
