# Generated by Django 4.2.6 on 2025-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_nssphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nssphoto',
            name='caption',
        ),
        migrations.AlterField(
            model_name='nssphoto',
            name='image',
            field=models.ImageField(upload_to='nss/'),
        ),
    ]
